<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Arial', sans-serif;
            font-size: 10px;
            color: #333;
            line-height: 1.4;
        }
        
        .header {
            background-color: #DAA520;
            color: white;
            padding: 20px;
            text-align: center;
            margin-bottom: 20px;
        }
        
        .header h1 {
            font-size: 22px;
            margin-bottom: 5px;
        }
        
        .header p {
            font-size: 11px;
        }
        
        .report-info {
            background-color: #f5f5f5;
            padding: 12px;
            margin-bottom: 20px;
            border-left: 4px solid #DAA520;
        }
        
        .report-info table {
            width: 100%;
        }
        
        .report-info td {
            padding: 4px;
            font-size: 10px;
        }
        
        .report-info td:first-child {
            font-weight: bold;
            width: 120px;
        }
        
        .section-title {
            background-color: #DAA520;
            color: white;
            padding: 8px 12px;
            font-size: 12px;
            font-weight: bold;
            margin: 20px 0 10px 0;
        }
        
        .summary-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        
        .summary-row {
            display: table-row;
        }
        
        .summary-item {
            display: table-cell;
            width: 50%;
            padding: 8px;
            border: 1px solid #ddd;
        }
        
        .summary-label {
            font-weight: bold;
            color: #666;
            font-size: 9px;
            margin-bottom: 3px;
        }
        
        .summary-value {
            font-size: 14px;
            font-weight: bold;
            color: #DAA520;
        }
        
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        table.data-table th {
            background-color: #f8f9fa;
            color: #333;
            padding: 8px;
            text-align: left;
            font-size: 9px;
            font-weight: bold;
            border-bottom: 2px solid #DAA520;
        }
        
        table.data-table td {
            padding: 6px 8px;
            border-bottom: 1px solid #eee;
            font-size: 9px;
        }
        
        table.data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        
        .badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
            text-transform: uppercase;
        }
        
        .badge-pending { background-color: #fef3c7; color: #92400e; }
        .badge-confirmed { background-color: #d1fae5; color: #065f46; }
        .badge-completed { background-color: #dbeafe; color: #1e40af; }
        .badge-cancelled { background-color: #fee2e2; color: #991b1b; }
        .badge-paid { background-color: #d1fae5; color: #065f46; }
        .badge-unpaid { background-color: #fef3c7; color: #92400e; }
        .badge-refunded { background-color: #fee2e2; color: #991b1b; }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8px;
            color: #999;
            padding: 10px;
            border-top: 1px solid #ddd;
        }
        
        .text-right {
            text-align: right;
        }
        
        .text-center {
            text-align: center;
        }
        
        .mt-4 {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Shine Spot Photography Studio</p>
    </div>
    
    <div class="report-info">
        <table>
            <tr>
                <td>Report Period:</td>
                <td>{{ $period['start'] }} - {{ $period['end'] }}</td>
            </tr>
            <tr>
                <td>Generated On:</td>
                <td>{{ $generated_at }}</td>
            </tr>
            <tr>
                <td>Generated By:</td>
                <td>{{ $generated_by }}</td>
            </tr>
        </table>
    </div>
    
    <div class="section-title">Summary Overview</div>
    
    <div class="summary-grid">
        <div class="summary-row">
            <div class="summary-item">
                <div class="summary-label">Total Revenue</div>
                <div class="summary-value">₱{{ number_format($summary['total_revenue'], 2) }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Total Bookings</div>
                <div class="summary-value">{{ $summary['total_bookings'] }}</div>
            </div>
        </div>
        <div class="summary-row">
            <div class="summary-item">
                <div class="summary-label">Total Expenses</div>
                <div class="summary-value">₱{{ number_format($summary['total_expenses'], 2) }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Net Profit</div>
                <div class="summary-value">₱{{ number_format($summary['net_profit'], 2) }}</div>
            </div>
        </div>
        <div class="summary-row">
            <div class="summary-item">
                <div class="summary-label">Paid Amount</div>
                <div class="summary-value">₱{{ number_format($summary['paid_amount'], 2) }}</div>
            </div>
            <div class="summary-item">
                <div class="summary-label">Unpaid Amount</div>
                <div class="summary-value">₱{{ number_format($summary['unpaid_amount'], 2) }}</div>
            </div>
        </div>
    </div>
    
    <div class="section-title">Booking Statistics</div>
    
    <table class="data-table">
        <tr>
            <td style="font-weight: bold;">Pending:</td>
            <td>{{ $summary['pending_bookings'] }}</td>
            <td style="font-weight: bold;">Confirmed:</td>
            <td>{{ $summary['confirmed_bookings'] }}</td>
        </tr>
        <tr>
            <td style="font-weight: bold;">Completed:</td>
            <td>{{ $summary['completed_bookings'] }}</td>
            <td style="font-weight: bold;">Cancelled:</td>
            <td>{{ $summary['cancelled_bookings'] }}</td>
        </tr>
    </table>
    
    <div class="section-title">Detailed Bookings</div>
    
    <table class="data-table">
        <thead>
            <tr>
                <th>Reference</th>
                <th>Client</th>
                <th>Package</th>
                <th>Date</th>
                <th>Status</th>
                <th>Payment</th>
                <th class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($bookings as $booking)
                <tr>
                    <td>{{ $booking->booking_reference }}</td>
                    <td>{{ $booking->client_first_name }} {{ $booking->client_last_name }}</td>
                    <td>{{ $booking->package->package_name ?? 'N/A' }}</td>
                    <td>{{ \Carbon\Carbon::parse($booking->booking_date)->format('M d, Y') }}</td>
                    <td>
                        <span class="badge badge-{{ $booking->status }}">{{ ucfirst($booking->status) }}</span>
                    </td>
                    <td>
                        <span class="badge badge-{{ $booking->payment_status }}">{{ ucfirst($booking->payment_status) }}</span>
                    </td>
                    <td class="text-right">₱{{ number_format($booking->total_amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" class="text-center">No bookings found for this period</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div style="page-break-before: always;"></div>
    
    <div class="section-title">Expenses</div>
    
    <table class="data-table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Description</th>
                <th class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($expenses as $expense)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($expense->expense_date)->format('M d, Y') }}</td>
                    <td>{{ $expense->category->category_name ?? 'N/A' }}</td>
                    <td>{{ $expense->description }}</td>
                    <td class="text-right">₱{{ number_format($expense->amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" class="text-center">No expenses found for this period</td>
                </tr>
            @endforelse
            @if($expenses->count() > 0)
                <tr style="font-weight: bold; background-color: #f5f5f5;">
                    <td colspan="3" class="text-right">Total Expenses:</td>
                    <td class="text-right">₱{{ number_format($expenses->sum('amount'), 2) }}</td>
                </tr>
            @endif
        </tbody>
    </table>
    
    <div class="footer">
        <p>This is a computer-generated report from Shine Spot Photography Studio Management System</p>
        <p>Page {PAGENO} of {nb}</p>
    </div>
</body>
</html>
