<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #DAA520;
            color: white;
            font-weight: bold;
        }
        .header-row {
            background-color: #f0f0f0;
            font-weight: bold;
        }
        .summary-label {
            font-weight: bold;
            background-color: #f8f9fa;
        }
        .total-row {
            font-weight: bold;
            background-color: #e8e8e8;
        }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <p><strong>Shine Spot Photography Studio</strong></p>
    <br>
    
    <table>
        <tr>
            <td class="summary-label">Report Period:</td>
            <td>{{ $period['start'] }} - {{ $period['end'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Generated On:</td>
            <td>{{ $generated_at }}</td>
        </tr>
        <tr>
            <td class="summary-label">Generated By:</td>
            <td>{{ $generated_by }}</td>
        </tr>
    </table>
    <br><br>
    
    <h2>Summary Overview</h2>
    <table>
        <tr>
            <th>Metric</th>
            <th>Value</th>
        </tr>
        <tr>
            <td class="summary-label">Total Revenue</td>
            <td>₱{{ number_format($summary['total_revenue'], 2) }}</td>
        </tr>
        <tr>
            <td class="summary-label">Total Bookings</td>
            <td>{{ $summary['total_bookings'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Total Expenses</td>
            <td>₱{{ number_format($summary['total_expenses'], 2) }}</td>
        </tr>
        <tr>
            <td class="summary-label">Net Profit</td>
            <td>₱{{ number_format($summary['net_profit'], 2) }}</td>
        </tr>
        <tr>
            <td class="summary-label">Pending Bookings</td>
            <td>{{ $summary['pending_bookings'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Confirmed Bookings</td>
            <td>{{ $summary['confirmed_bookings'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Completed Bookings</td>
            <td>{{ $summary['completed_bookings'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Cancelled Bookings</td>
            <td>{{ $summary['cancelled_bookings'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Paid Amount</td>
            <td>₱{{ number_format($summary['paid_amount'], 2) }}</td>
        </tr>
        <tr>
            <td class="summary-label">Unpaid Amount</td>
            <td>₱{{ number_format($summary['unpaid_amount'], 2) }}</td>
        </tr>
    </table>
    <br><br>
    
    <h2>Detailed Bookings</h2>
    <table>
        <thead>
            <tr>
                <th>Reference</th>
                <th>Client Name</th>
                <th>Package</th>
                <th>Date</th>
                <th>Status</th>
                <th>Payment Status</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($bookings as $booking)
                <tr>
                    <td>{{ $booking->booking_reference }}</td>
                    <td>{{ $booking->client_first_name }} {{ $booking->client_last_name }}</td>
                    <td>{{ $booking->package->package_name ?? 'N/A' }}</td>
                    <td>{{ \Carbon\Carbon::parse($booking->booking_date)->format('M d, Y') }}</td>
                    <td>{{ ucfirst($booking->status) }}</td>
                    <td>{{ ucfirst($booking->payment_status) }}</td>
                    <td>₱{{ number_format($booking->total_amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No bookings found for this period</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    <br><br>
    
    <h2>Expenses</h2>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Description</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($expenses as $expense)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($expense->expense_date)->format('M d, Y') }}</td>
                    <td>{{ $expense->category->category_name ?? 'N/A' }}</td>
                    <td>{{ $expense->description }}</td>
                    <td>₱{{ number_format($expense->amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center;">No expenses found for this period</td>
                </tr>
            @endforelse
            @if($expenses->count() > 0)
                <tr class="total-row">
                    <td colspan="3" style="text-align: right;">Total Expenses:</td>
                    <td>₱{{ number_format($expenses->sum('amount'), 2) }}</td>
                </tr>
            @endif
        </tbody>
    </table>
</body>
</html>
