<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #DAA520;
            color: white;
            font-weight: bold;
        }
        .header-row {
            background-color: #f0f0f0;
            font-weight: bold;
        }
        .summary-label {
            font-weight: bold;
            background-color: #f8f9fa;
        }
        .total-row {
            font-weight: bold;
            background-color: #e8e8e8;
        }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <p><strong>Shine Spot Photography Studio</strong></p>
    <br>
    
    <table>
        <tr>
            <td class="summary-label">Report Period:</td>
            <td>{{ $period['start'] }} - {{ $period['end'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Generated On:</td>
            <td>{{ $generated_at }}</td>
        </tr>
        <tr>
            <td class="summary-label">Generated By:</td>
            <td>{{ $generated_by }}</td>
        </tr>
    </table>
    <br><br>
    
    <h2>Summary Overview</h2>
    <table>
        <tr>
            <th>Metric</th>
            <th>Value</th>
        </tr>
        <tr>
            <td class="summary-label">Total Transactions</td>
            <td>{{ $summary['total_transactions'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Total Amount</td>
            <td>₱{{ number_format($summary['total_amount'], 2) }}</td>
        </tr>
        <tr>
            <td class="summary-label">GCash Transactions</td>
            <td>{{ $summary['gcash_transactions'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">GCash Amount</td>
            <td>₱{{ number_format($summary['gcash_amount'], 2) }}</td>
        </tr>
        <tr>
            <td class="summary-label">Cash Transactions</td>
            <td>{{ $summary['cash_transactions'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Cash Amount</td>
            <td>₱{{ number_format($summary['cash_amount'], 2) }}</td>
        </tr>
        <tr>
            <td class="summary-label">Card Transactions</td>
            <td>{{ $summary['card_transactions'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Card Amount</td>
            <td>₱{{ number_format($summary['card_amount'], 2) }}</td>
        </tr>
        <tr>
            <td class="summary-label">Successful Transactions</td>
            <td>{{ $summary['successful_transactions'] }}</td>
        </tr>
        <tr>
            <td class="summary-label">Pending Transactions</td>
            <td>{{ $summary['pending_transactions'] }}</td>
        </tr>
    </table>
    <br><br>
    
    <h2>Payment Transactions</h2>
    <table>
        <thead>
            <tr>
                <th>Transaction ID</th>
                <th>Date</th>
                <th>Booking Ref</th>
                <th>Client</th>
                <th>Method</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Reference</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $transaction)
                <tr>
                    <td>{{ $transaction->transaction_id }}</td>
                    <td>{{ \Carbon\Carbon::parse($transaction->payment_date)->format('M d, Y h:i A') }}</td>
                    <td>{{ $transaction->booking->booking_reference ?? 'N/A' }}</td>
                    <td>{{ $transaction->booking->client_first_name ?? '' }} {{ $transaction->booking->client_last_name ?? '' }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $transaction->payment_method)) }}</td>
                    <td>₱{{ number_format($transaction->amount, 2) }}</td>
                    <td>{{ $transaction->xendit_status }}</td>
                    <td>{{ $transaction->transaction_reference ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No transactions found for this period</td>
                </tr>
            @endforelse
            @if($transactions->count() > 0)
                <tr class="total-row">
                    <td colspan="5" style="text-align: right;">Total:</td>
                    <td>₱{{ number_format($transactions->sum('amount'), 2) }}</td>
                    <td colspan="2"></td>
                </tr>
            @endif
        </tbody>
    </table>
</body>
</html>
